import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

const getPermission = async () => {
  const res = await fetch(
    `https://61192b408ed292001799eeb2.mockapi.io/permission`
  );
  const { url } = await res.json();
  return url;
};
export default function Home() {
  const { push } = useRouter();
  const hasPermission = true;
  const [iframeUrl, setIframeUrl] = useState(null);

  useEffect(() => {
    if (!hasPermission) push(`/nopermission`);
    getPermission().then((url) => setIframeUrl(url));
  }, []);

  if (!iframeUrl) return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title> Next App </title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div style={{ height: '100vh' }}>
        <iframe src={iframeUrl} width='100%' height='100%' />
      </div>
    </>
  );
}
